In [5]:
import pandas as pd
from collections import defaultdict
import itertools

import sys
sys.path.append("..")
from create_dataset.fasta_to_df import fasta_to_df, all_data_df_to_arange_df

N = 3
BASE = ["A", "T", "G", "C"]
N_BASE = ["".join(i) for i in list(itertools.product(BASE, repeat=N))]
DATA_COLUMNS = ["year", "month", "day"]
CLADE_COLUMNS = ["clade", "head2"]

JAPAN_HEADER_COLUMNS = ["head", "ID", "date"]
ALL_DATA_HEADER_COLUMNS = ["head", "id", "continent", "country", "city", "host", "clade_head", "date"]


In [10]:
header, feature = fasta_to_df("all_data_odd_tri", N, ALL_DATA_HEADER_COLUMNS, N_BASE)

In [11]:
data = all_data_df_to_arange_df(header, feature)

In [12]:
data

head              id continent         country  \
0          >Wuhan/IVDC-HB-01/2019  EPI_ISL_402119      Asia           China   
1          >Wuhan/IVDC-HB-04/2020  EPI_ISL_402120      Asia           China   
2          >Wuhan/IVDC-HB-05/2019  EPI_ISL_402121      Asia           China   
3       >Wuhan/IPBCAMS-WH-01/2019  EPI_ISL_402123      Asia           China   
4               >Wuhan/WIV04/2019  EPI_ISL_402124      Asia           China   
...                           ...             ...       ...             ...   
130748  >England/MILK-A7CA70/2020  EPI_ISL_606426    Europe  United_Kingdom   
130749  >England/MILK-A7D541/2020  EPI_ISL_606428    Europe  United_Kingdom   
130750  >England/MILK-A7DC6A/2020  EPI_ISL_606429    Europe  United_Kingdom   
130751  >England/MILK-A7D14D/2020  EPI_ISL_606430    Europe  United_Kingdom   
130752  >England/MILK-A7D6E4/2020  EPI_ISL_606431    Europe  United_Kingdom   

           city   host                    clade_head        date  year month  \
0         Hubei  Human      L_>Wuhan/IVDC-HB-01/2019  2019-12-30  2019    12   
1         Hubei  Human      L_>Wuhan/IVDC-HB-04/2020  2020-01-01  2020    01   
2         Hubei  Human      L_>Wuhan/IVDC-HB-05/2019  2019-12-30  2019    12   
3         Hubei  Human   L_>Wuhan/IPBCAMS-WH-01/2019  2019-12-24  2019    12   
4         Hubei  Human           L_>Wuhan/WIV04/2019  2019-12-30  2019    12   
...         ...    ...                           ...         ...   ...   ...   
130748  England  Human  GR_>England/MILK-A7CA70/2020  2020-10-15  2020    10   
130749  England  Human  GR_>England/MILK-A7D541/2020  2020-10-13  2020    10   
130750  England  Human   G_>England/MILK-A7DC6A/2020  2020-10-13  2020    10   
130751  England  Human  GV_>England/MILK-A7D14D/2020  2020-10-13  2020    10   
130752  England  Human  GV_>England/MILK-A7D6E4/2020  2020-10-13  2020    10   

        ...       CTG       CTC       CGA       CGT       CGG       CGC  \
0       ...  1.429849  0.885187  0.295150  0.493948  0.359235  0.489559   
1       ...  1.430071  0.885648  0.295258  0.494025  0.359366  0.489916   
2       ...  1.430337  0.885187  0.295185  0.491227  0.354750  0.489726   
3       ...  1.429510  0.885280  0.298189  0.493831  0.358990  0.489392   
4       ...  1.429849  0.885187  0.295150  0.493948  0.359235  0.489559   
...     ...       ...       ...       ...       ...       ...       ...   
130748  ...  1.437784  0.884368  0.296599  0.489890  0.360747  0.487794   
130749  ...  1.435984  0.883813  0.296628  0.490265  0.361356  0.493020   
130750  ...  1.435568  0.887113  0.290215  0.484323  0.360840  0.497647   
130751  ...  1.432720  0.888261  0.293622  0.490141  0.361068  0.493501   
130752  ...  1.435166  0.885016  0.293501  0.489986  0.356009  0.493152   

             CCA       CCT       CCG       CCC  
0       1.174333  1.060991  0.373478  0.625114  
1       1.175189  1.058457  0.373750  0.625798  
2       1.177387  1.060991  0.368557  0.625114  
3       1.174465  1.061102  0.373350  0.625114  
4       1.174333  1.060991  0.373478  0.625114  
...          ...       ...       ...       ...  
130748  1.169741  1.061242  0.370927  0.625517  
130749  1.168228  1.060576  0.376118  0.613964  
130750  1.174827  1.057712  0.370696  0.624579  
130751  1.167419  1.059081  0.376485  0.604756  
130752  1.167122  1.058914  0.376219  0.615314  

[130740 rows x 77 columns]

In [13]:
data = data[data["clade"] != "O"]
data["clade"] = data["clade"].map({"G":0, "GH":1, "GR":2, "GV":3, "L":4, "S":5, "V":6})
data

c:\users\ryuki\anaconda3\envs\ghsom\lib\site-packages\ipykernel_launcher.py:2: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  


head              id continent         country  \
0          >Wuhan/IVDC-HB-01/2019  EPI_ISL_402119      Asia           China   
1          >Wuhan/IVDC-HB-04/2020  EPI_ISL_402120      Asia           China   
2          >Wuhan/IVDC-HB-05/2019  EPI_ISL_402121      Asia           China   
3       >Wuhan/IPBCAMS-WH-01/2019  EPI_ISL_402123      Asia           China   
4               >Wuhan/WIV04/2019  EPI_ISL_402124      Asia           China   
...                           ...             ...       ...             ...   
130748  >England/MILK-A7CA70/2020  EPI_ISL_606426    Europe  United_Kingdom   
130749  >England/MILK-A7D541/2020  EPI_ISL_606428    Europe  United_Kingdom   
130750  >England/MILK-A7DC6A/2020  EPI_ISL_606429    Europe  United_Kingdom   
130751  >England/MILK-A7D14D/2020  EPI_ISL_606430    Europe  United_Kingdom   
130752  >England/MILK-A7D6E4/2020  EPI_ISL_606431    Europe  United_Kingdom   

           city   host                    clade_head        date  year month  \
0         Hubei  Human      L_>Wuhan/IVDC-HB-01/2019  2019-12-30  2019    12   
1         Hubei  Human      L_>Wuhan/IVDC-HB-04/2020  2020-01-01  2020    01   
2         Hubei  Human      L_>Wuhan/IVDC-HB-05/2019  2019-12-30  2019    12   
3         Hubei  Human   L_>Wuhan/IPBCAMS-WH-01/2019  2019-12-24  2019    12   
4         Hubei  Human           L_>Wuhan/WIV04/2019  2019-12-30  2019    12   
...         ...    ...                           ...         ...   ...   ...   
130748  England  Human  GR_>England/MILK-A7CA70/2020  2020-10-15  2020    10   
130749  England  Human  GR_>England/MILK-A7D541/2020  2020-10-13  2020    10   
130750  England  Human   G_>England/MILK-A7DC6A/2020  2020-10-13  2020    10   
130751  England  Human  GV_>England/MILK-A7D14D/2020  2020-10-13  2020    10   
130752  England  Human  GV_>England/MILK-A7D6E4/2020  2020-10-13  2020    10   

        ...       CTG       CTC       CGA       CGT       CGG       CGC  \
0       ...  1.429849  0.885187  0.295150  0.493948  0.359235  0.489559   
1       ...  1.430071  0.885648  0.295258  0.494025  0.359366  0.489916   
2       ...  1.430337  0.885187  0.295185  0.491227  0.354750  0.489726   
3       ...  1.429510  0.885280  0.298189  0.493831  0.358990  0.489392   
4       ...  1.429849  0.885187  0.295150  0.493948  0.359235  0.489559   
...     ...       ...       ...       ...       ...       ...       ...   
130748  ...  1.437784  0.884368  0.296599  0.489890  0.360747  0.487794   
130749  ...  1.435984  0.883813  0.296628  0.490265  0.361356  0.493020   
130750  ...  1.435568  0.887113  0.290215  0.484323  0.360840  0.497647   
130751  ...  1.432720  0.888261  0.293622  0.490141  0.361068  0.493501   
130752  ...  1.435166  0.885016  0.293501  0.489986  0.356009  0.493152   

             CCA       CCT       CCG       CCC  
0       1.174333  1.060991  0.373478  0.625114  
1       1.175189  1.058457  0.373750  0.625798  
2       1.177387  1.060991  0.368557  0.625114  
3       1.174465  1.061102  0.373350  0.625114  
4       1.174333  1.060991  0.373478  0.625114  
...          ...       ...       ...       ...  
130748  1.169741  1.061242  0.370927  0.625517  
130749  1.168228  1.060576  0.376118  0.613964  
130750  1.174827  1.057712  0.370696  0.624579  
130751  1.167419  1.059081  0.376485  0.604756  
130752  1.167122  1.058914  0.376219  0.615314  

[127588 rows x 77 columns]

In [9]:
data["clade"]

0          L
1          L
2          L
3          L
4          L
          ..
130748    GR
130749    GR
130750     G
130751    GV
130752    GV
Name: clade, Length: 130740, dtype: object

In [14]:
data[N_BASE]

AAA       AAT       AAG       AAC       ATA       ATT       ATG  \
0       1.121311  0.889429  1.109262  1.255885  0.550487  0.839984  1.287390   
1       1.121311  0.890412  1.109262  1.254300  0.550373  0.839634  1.287121   
2       1.120557  0.889030  1.109144  1.255322  0.550241  0.839796  1.289319   
3       1.120431  0.889721  1.109133  1.254124  0.550668  0.841341  1.287229   
4       1.121311  0.889429  1.109262  1.255885  0.550487  0.839984  1.287390   
...          ...       ...       ...       ...       ...       ...       ...   
130748  1.124244  0.888012  1.110720  1.258818  0.551786  0.838630  1.287748   
130749  1.123609  0.888277  1.108694  1.256943  0.548882  0.840508  1.284917   
130750  1.125554  0.890246  1.110343  1.249080  0.550547  0.843685  1.283196   
130751  1.122225  0.892110  1.108493  1.252782  0.551422  0.841352  1.283849   
130752  1.122604  0.890154  1.108363  1.254888  0.549319  0.840711  1.285603   

             ATC       AGA       AGT  ...       CTG       CTC       CGA  \
0       0.643635  1.157075  0.901528  ...  1.429849  0.885187  0.295150   
1       0.645634  1.157075  0.901340  ...  1.430071  0.885648  0.295258   
2       0.643491  1.156951  0.901634  ...  1.430337  0.885187  0.295185   
3       0.643774  1.156940  0.901416  ...  1.429510  0.885280  0.298189   
4       0.643635  1.157075  0.901528  ...  1.429849  0.885187  0.295150   
...          ...       ...       ...  ...       ...       ...       ...   
130748  0.642538  1.156761  0.903027  ...  1.437784  0.884368  0.296599   
130749  0.640104  1.158566  0.908887  ...  1.435984  0.883813  0.296628   
130750  0.644275  1.158286  0.903584  ...  1.435568  0.887113  0.290215   
130751  0.646426  1.158356  0.899228  ...  1.432720  0.888261  0.293622   
130752  0.640794  1.158220  0.900990  ...  1.435166  0.885016  0.293501   

             CGT       CGG       CGC       CCA       CCT       CCG       CCC  
0       0.493948  0.359235  0.489559  1.174333  1.060991  0.373478  0.625114  
1       0.494025  0.359366  0.489916  1.175189  1.058457  0.373750  0.625798  
2       0.491227  0.354750  0.489726  1.177387  1.060991  0.368557  0.625114  
3       0.493831  0.358990  0.489392  1.174465  1.061102  0.373350  0.625114  
4       0.493948  0.359235  0.489559  1.174333  1.060991  0.373478  0.625114  
...          ...       ...       ...       ...       ...       ...       ...  
130748  0.489890  0.360747  0.487794  1.169741  1.061242  0.370927  0.625517  
130749  0.490265  0.361356  0.493020  1.168228  1.060576  0.376118  0.613964  
130750  0.484323  0.360840  0.497647  1.174827  1.057712  0.370696  0.624579  
130751  0.490141  0.361068  0.493501  1.167419  1.059081  0.376485  0.604756  
130752  0.489986  0.356009  0.493152  1.167122  1.058914  0.376219  0.615314  

[127588 rows x 64 columns]

In [64]:
import pandas as pd
import numpy as np
from sklearn.preprocessing import MinMaxScaler, StandardScaler
from matplotlib import pyplot as plt
from sklearn.model_selection import train_test_split
import time
from keras import models
from keras import layers

from tensorflow.keras.callbacks import EarlyStopping, ModelCheckpoint

In [65]:
scaler = StandardScaler()

feature = scaler.fit_transform(data[N_BASE])

output_dim = 7
x_train, x_test, y_train, y_test = train_test_split(feature, data["clade"],
                                                    test_size=0.2,
                                                    random_state=42,
                                                    shuffle= True)


# ニューラルネットワークの作成を開始
network = models.Sequential([
    layers.Dense(units=256, activation="relu", input_shape=(feature.shape[1],)),
    layers.Dropout(0.3),
    layers.Dense(units=256, activation="relu"),
    layers.Dropout(0.3),
    layers.Dense(units=256, activation="relu"),
    layers.Dense(units=output_dim, activation="softmax")
])

# ニューラルネットワークをコンパイル
network.compile(loss='sparse_categorical_crossentropy',
                optimizer="adam",
                metrics=["accuracy"])

callbacks = [
    EarlyStopping(patience=3),
    # ModelCheckpoint(model_path, save_best_only=True)
]

# ニューラルネットワークを訓練
hist = network.fit(x_train,
                      y_train,
                      epochs=50,
                      verbose=1,
                      batch_size=128,
                      validation_split = 0.2,
                      callbacks=callbacks)

# テストセットのクラスを予測
# predicted_target = network.predict(features_test)

Epoch 1/50
638/638 [==============================] - 3s 3ms/step - loss: 0.2392 - accuracy: 0.9221 - val_loss: 0.0118 - val_accuracy: 0.9960
Epoch 2/50
638/638 [==============================] - 2s 3ms/step - loss: 0.0279 - accuracy: 0.9918 - val_loss: 0.0117 - val_accuracy: 0.9965
Epoch 3/50
638/638 [==============================] - 2s 3ms/step - loss: 0.0163 - accuracy: 0.9950 - val_loss: 0.0120 - val_accuracy: 0.9962
Epoch 4/50
638/638 [==============================] - 2s 3ms/step - loss: 0.0157 - accuracy: 0.9942 - val_loss: 0.0071 - val_accuracy: 0.9977
Epoch 5/50
638/638 [==============================] - 2s 3ms/step - loss: 0.0122 - accuracy: 0.9961 - val_loss: 0.0108 - val_accuracy: 0.9966
Epoch 6/50
638/638 [==============================] - 2s 3ms/step - loss: 0.0124 - accuracy: 0.9956 - val_loss: 0.0084 - val_accuracy: 0.9970
Epoch 7/50
638/638 [==============================] - 2s 3ms/step - loss: 0.0095 - accuracy: 0.9968 - val_loss: 0.0070 - val_accuracy: 0.9975
Epoch 

In [66]:
from sklearn.metrics import confusion_matrix, accuracy_score

y_true = y_test
y_pred = network.predict_classes(x_test)

cm = confusion_matrix(y_true, y_pred)
print(accuracy_score(y_true, y_pred))
print(cm)

c:\users\ryuki\anaconda3\envs\ghsom\lib\site-packages\tensorflow\python\keras\engine\sequential.py:450: UserWarning: `model.predict_classes()` is deprecated and will be removed after 2021-01-01. Please use instead:* `np.argmax(model.predict(x), axis=-1)`,   if your model does multi-class classification   (e.g. if it uses a `softmax` last-layer activation).* `(model.predict(x) > 0.5).astype("int32")`,   if your model does binary classification   (e.g. if it uses a `sigmoid` last-layer activation).
  warnings.warn('`model.predict_classes()` is deprecated and '


0.9981973508895682
[[ 4572     7    19     3     0     0     2]
 [   10  6091     0     1     0     0     0]
 [    1     0 10149     0     0     0     0]
 [    1     0     1  2110     0     0     0]
 [    0     0     0     0   689     0     1]
 [    0     0     0     0     0  1079     0]
 [    0     0     0     0     0     0   782]]
